name: Build, Pack & Publish DEVELOP nuget prerelease packages

on:
  push:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.105
    - name: Build with dotnet
      run: dotnet build --configuration Debug --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
      shell: bash
    - name: Publish nuget
      run: |
           for f in ./Robot.MessageBus/bin/Debug/*.nupkg
           do
             curl -vX PUT -u "nahueltaibo:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/nahueltaibo/
           done
      shell: bash
      working-directory: ./src
