name: Build, Pack & Publish DEVELOP nuget prerelease packages

on:
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.105
    - name: Go to solution
      run: cd src
    - name: Build with dotnet
      run: dotnet build --configuration Debug
    - name: Setup nuget config
      run: sed 's/GITHUB_TOKEN/${{secrets.GithubPackagePublisher }}/g' ./nuget.config > nuget.config
    - name: Publish nuget
      run: dotnet nuget push ./Robot.MessageBus/bin/Debug/*.nupkg -s "github"
