name: Build, Pack & Publish DEVELOP nuget prerelease packages

on:
  push:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.105
    - name: Build with dotnet
      run: dotnet build "./src/NetCoreRover.sln" --configuration Debug
    - name: Setup nuget config
      run: sed 's/GITHUB_TOKEN/${{secrets.GithubPackagePublisher }}/g' ./src/nuget.config > ./src/nuget.config
    - name: Publish nuget
      run: dotnet nuget push src/Robot.MessageBus/bin/Debug/*.nupkg -s "github"
